<a href="https://colab.research.google.com/github/mahananda123/PhishingDetectionUsingML/blob/main/URLFeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
!wget http://data.phishtank.com/data/online-valid.csv

--2024-01-24 19:17:35--  http://data.phishtank.com/data/online-valid.csv
Resolving data.phishtank.com (data.phishtank.com)... 104.16.101.75, 104.17.177.85, 2606:4700::6810:654b, ...
Connecting to data.phishtank.com (data.phishtank.com)|104.16.101.75|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://data.phishtank.com/data/online-valid.csv [following]
--2024-01-24 19:17:35--  https://data.phishtank.com/data/online-valid.csv
Connecting to data.phishtank.com (data.phishtank.com)|104.16.101.75|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn.phishtank.com/datadumps/verified_online.csv?Expires=1706123625&Signature=IhL2cly1vjNVejsqc8OEiQ2j4p4cIt-RImV7k9ZDiVaoIEuqdoWQUM8s1qwy2E81iZR4k29KSjYyE58dTLs7EwWbIYORKhCtRGHfTSkLSU7eWb9IHBQ8pGuNBcLIirOwGA7geRp5BuA4PO4jL-PAOqmWKSZF4hcV5WUr6f3E-HNQvXdFO2nibp0hZcs07D3YvpWJK-80zdt~~FOfUMFwEfU9vcGOMztEY1fQDWCrSJlSxbIZAA8zVacAoBSFOKVV4iOVklpJ8EqxID6CZEt6fhwkpKYEkZRUUN1BiOuPy~~0fqUe-Si~Cgld7v1e2WUgp~eAS9tzxXCkPq136-5PQQ__&Key-Pair-Id=APKAILB45UG3RB4CSOJA [following]
--2024-01-24 19:17:35--  https://cdn.phishtank.com/datadumps/verified_online.csv?Expires=1706123625&Signature=IhL2cly1vjNVejsqc8OEiQ2j4p4cIt-RImV7k9ZDiVaoIEuqdoWQUM8s1qwy2E81iZR4k29KSjYyE58dTLs7EwWbIYORKhCtRGHfTSkLSU7eWb9IHBQ8pGuNBcLIirOwGA7geRp5BuA4PO4jL-PAOqmWKSZF4hcV5WUr6f3E-HNQvXdFO2nibp0hZcs07D3YvpWJK-80zdt~~FOfUMFwEfU9vcGOMztEY1fQDWCrSJlSxbIZAA8zVacAoBSFOKVV4iOVklpJ8EqxID6CZEt6fhwkpKYEkZRUUN1BiOuPy~~0fqUe-Si~Cgld7v1e2WUgp~eAS9tzxXCkPq136-5PQQ__&Key-Pair-Id=APKAILB45UG3RB4CSOJA
Resolving cdn.phishtank.com (cdn.phishtank.com)... 104.17.177.85, 104.16.101.75, 2606:4700::6811:b155, ...
Connecting to cdn.phishtank.com (cdn.phishtank.com)|104.17.177.85|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-01-24 19:17:35 ERROR 404: Not Found.

In [ ]:
data=pd.read_csv("/content/online-valid.csv")
data.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,6557033,http://u1047531.cp.regruhosting.ru/acces-inges...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T22:01:43+00:00,yes,2020-05-09T22:03:07+00:00,yes,Other
1,6557032,http://hoysalacreations.com/wp-content/plugins...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T22:01:37+00:00,yes,2020-05-09T22:03:07+00:00,yes,Other
2,6557011,http://www.accsystemprblemhelp.site/checkpoint...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T21:54:31+00:00,yes,2020-05-09T21:55:38+00:00,yes,Facebook
3,6557010,http://www.accsystemprblemhelp.site/login_atte...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T21:53:48+00:00,yes,2020-05-09T21:54:34+00:00,yes,Facebook
4,6557009,https://firebasestorage.googleapis.com/v0/b/so...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T21:49:27+00:00,yes,2020-05-09T21:51:24+00:00,yes,Microsoft

In [ ]:
data.shape

(14858, 8)

In [ ]:
# collect 10000 phishing URL's randomly
phishurl = data.sample(n=10000, random_state=12).copy()
phishurl = phishurl.reset_index(drop=True)
phishurl.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,6514946,http://confirmprofileaccount.com/,http://www.phishtank.com/phish_detail.php?phis...,2020-04-19T11:06:55+00:00,yes,2020-04-19T13:42:41+00:00,yes,Other
1,4927651,http://www.marreme.com/MasterAdmin/04mop.html,http://www.phishtank.com/phish_detail.php?phis...,2017-04-04T19:35:54+00:00,yes,2017-05-03T23:00:42+00:00,yes,Other
2,5116976,http://modsecpaststudents.com/review/,http://www.phishtank.com/phish_detail.php?phis...,2017-07-25T18:48:30+00:00,yes,2017-07-28T16:01:36+00:00,yes,Other
3,6356131,https://docs.google.com/forms/d/e/1FAIpQLScL6L...,http://www.phishtank.com/phish_detail.php?phis...,2020-01-13T20:13:37+00:00,yes,2020-01-17T01:55:38+00:00,yes,Other
4,6535965,https://oportunidadedasemana.com/americanas//?...,http://www.phishtank.com/phish_detail.php?phis...,2020-04-29T00:01:03+00:00,yes,2020-05-01T10:55:35+00:00,yes,Other

In [ ]:
data['target'].unique()

array(['Other', 'Facebook', 'Microsoft', 'Banco Santander, S.A.',
       'ING Direct', 'ABSA Bank', 'Google', 'American Express', 'Three',
       'DHL', 'Bank of America Corporation', 'Steam', 'RuneScape',
       'Twitter', 'Comcast', 'Amazon.com', 'PayPal',
       'Development Bank of Singapore', 'Wells Fargo', 'Scotiabank',
       'Caixa', 'JPMorgan Chase and Co.', 'Coinbase', 'eBay, Inc.',
       'Sulake Corporation', 'EE', 'Apple', 'Itau', 'Bank of the West',
       'Netflix', 'Internal Revenue Service', 'Nantucket Bank',
       'UniCredit', 'Banco De Brasil', 'Santander UK', 'Citibank',
       'PKO Polish Bank', "Her Majesty's Revenue and Customs",
       'Poste Italiane', 'Americanas.com', 'Telefónica UK', 'HSBC Group',
       'Accurint', 'LocalBitcoins.com', 'Bradesco', 'Capitec Bank',
       'Nationwide Building Society', 'AOL', 'Delta Air Lines',
       'Bank Millennium', 'Vodafone', 'Blockchain', 'Rabobank', 'Nubank',
       'Virustotal', 'Paxful', 'DocuSign', 'Comerica Bank', 'Tesco',
       'AT&amp;T', 'Western Union', 'Rackspace', 'Alibaba.com', 'Visa',
       'Hotmail', 'Banca Intesa', 'Cox Communications', 'Adobe',
       'ABN AMRO Bank', 'Allegro', 'BMO Financial', 'Pintrest',
       'Aetna Health Plans &amp; Dental Coverage', 'Orange', 'Dropbox',
       'Salesforce', 'Swedbank', 'CIMB Bank', 'Alliance Bank', 'Yahoo',
       'Banco Real', 'WhatsApp', 'Westpac', 'Cartasi', 'Suncorp',
       'MyEtherWallet', 'ASB Bank Limited', 'Lloyds Bank',
       'Volksbanken Raiffeisenbanken', 'PNC Bank', 'WalMart',
       'Branch Banking and Trust Company', 'Live',
       'United Services Automobile Association', 'Royal Bank of Scotland'],
      dtype=object)

In [ ]:
phishurl.shape

(10000, 8)

# 2.2 Legitimate URL's

In [ ]:
data1 = pd.read_csv("/content/Benign_list_big_final.csv")
data1.columns = ['URLs']
data1.head()

                                                URLs
0  http://1337x.to/torrent/1110018/Blackhat-2015-...
1  http://1337x.to/torrent/1122940/Blackhat-2015-...
2  http://1337x.to/torrent/1124395/Fast-and-Furio...
3  http://1337x.to/torrent/1145504/Avengers-Age-o...
4  http://1337x.to/torrent/1160078/Avengers-age-o...

In [ ]:
data1.shape

(35377, 1)

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35377 entries, 0 to 35376
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   URLs    35377 non-null  object
dtypes: object(1)
memory usage: 276.5+ KB

In [ ]:
legiurl=data1.sample(n=15000, random_state=12).copy()
legiurl=legiurl.reset_index(drop=True)
legiurl.head()

                                                URLs
0  http://graphicriver.net/search?date=this-month...
1  http://ecnavi.jp/redirect/?url=http://www.cros...
2  https://hubpages.com/signin?explain=follow+Hub...
3  http://extratorrent.cc/torrent/4190536/AOMEI+B...
4  http://icicibank.com/Personal-Banking/offers/o...

In [ ]:
legiurl.shape

(15000, 1)

# 3. Feature Extraction:
In this step, features are extracted from the URLs dataset.

The extracted features are categorized into

1. Address Bar based Features
2. Domain based Features
3. HTML & Javascript based Features

# 3.1. Address Bar Based Features:
Many features can be extracted that can be consided as address bar base features. Out of them, below mentioned were considered for this project.

1. Domain of URL
2. IP Address in URL
3. "@" Symbol in URL
4. Length of URL
5. Depth of URL
6. Redirection "//" in URL
7. "http/https" in Domain name
8. Using URL Shortening Services “TinyURL”
9. Prefix or Suffix "-" in Domain

Each of these features are explained and the coded below:

In [ ]:
# importing required packages for this section
from urllib.parse import urlparse,urlencode
import ipaddress
import re

#3.1.1. Domain of the URL
Here, we are just extracting the domain present in the URL. This feature doesn't have much significance in the training. May even be dropped while training the model.

In [ ]:
# 1. Domain of the url (Domain)
def getDomain(url):
  domain=urlparse(url).netloc
  if re.match(r"^www.",domain):
    domain=domain.replace("www.","")
  return domain

# 3.1.2. IP Address in the URL
Checks for the presence of IP address in the URL. URLs may have IP address instead of domain name. If an IP address is used as an alternative of the domain name in the URL, we can be sure that someone is trying to steal personal information with this URL.

If the domain part of URL has IP address, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 2.checks for IP addressin URL
def havingIP(url):
  try:
    ipaddress.ip_address(url)
    ip=1
  except:
    ip=0
  return ip

# 3.1.3. "@" Symbol in URL
Checks for the presence of '@' symbol in the URL. Using “@” symbol in the URL leads the browser to ignore everything preceding the “@” symbol and the real address often follows the “@” symbol.

If the URL has '@' symbol, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 3.Checks the presence of @ in URL
def haveAtSign(url):
  if "@" in url:
    at=1
  else:
    at=0
  return at

# 3.1.4. Length of URL
Computes the length of the URL. Phishers can use long URL to hide the doubtful part in the address bar. In this project, if the length of the URL is greater than or equal 54 characters then the URL classified as phishing otherwise legitimate.

If the length of URL >= 54 , the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 4. Finding the length of URL and categorizing(URL_Length)
def getLength(url):
  if len(url)< 54:
    length=0
  else:
    length=1
  return length

# 3.1.5. Depth of URL
Computes the depth of the URL. This feature calculates the number of sub pages in the given url based on the '/'.

The value of feature is a numerical based on the URL.

In [ ]:
# 5.Gives number of '/' in URL(URL_Depth)
def getDepth(url):
  s=urlparse(url).path.split('/')
  depth=0
  for j in range(len(s)):
    if len(s[j]) !=0:
      depth+=1
  return depth

#3.1.6. Redirection "//" in URL
Checks the presence of "//" in the URL. The existence of “//” within the URL path means that the user will be redirected to another website. The location of the “//” in URL is computed. We find that if the URL starts with “HTTP”, that means the “//” should appear in the sixth position. However, if the URL employs “HTTPS” then the “//” should appear in seventh position.

If the "//" is anywhere in the URL apart from after the protocal, thee value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 6. Checking for redirection '//' in the url
def redirection(url):
  pos=url.rfind('//')
  if pos>6:
    if pos>7:
      return 1
    else:
      return 0
  return 0

# 3.1.7. "http/https" in Domain name
Checks for the presence of "http/https" in the domain part of the URL. The phishers may add the “HTTPS” token to the domain part of a URL in order to trick users.

If the URL has "http/https" in the domain part, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 7.Existence of “HTTPS” Token in the Domain Part of the URL (https_Domain)
def httpDomain(url):
  domain = urlparse(url).netloc
  if 'https' in domain:
    return 1
  else:
    return 0

#3.1.8. Using URL Shortening Services “TinyURL”
URL shortening is a method on the “World Wide Web” in which a URL may be made considerably smaller in length and still lead to the required webpage. This is accomplished by means of an “HTTP Redirect” on a domain name that is short, which links to the webpage that has a long URL.

If the URL is using Shortening Services, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
#listing shortening services
shortening_services = r"bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|" \
                      r"yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|" \
                      r"short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|" \
                      r"doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|db\.tt|" \
                      r"qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|q\.gs|is\.gd|" \
                      r"po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|x\.co|" \
                      r"prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|" \
                      r"tr\.im|link\.zip\.net"

In [ ]:
# 8. Checking for Shortening Services in URL (Tiny_URL)
def tinyURL(url):
    match=re.search(shortening_services,url)
    if match:
        return 1
    return 0

# 3.1.9. Prefix or Suffix "-" in Domain
Checking the presence of '-' in the domain part of URL. The dash symbol is rarely used in legitimate URLs. Phishers tend to add prefixes or suffixes separated by (-) to the domain name so that users feel that they are dealing with a legitimate webpage.

If the URL has '-' symbol in the domain part of the URL, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 9.Checking for prefix or suffix y (-) in the domain
def prefixSuffix(url):
  if '-' in urlparse(url).netloc:
    return 1
  return 0

# 3.2. Domain Based Features:
Many features can be extracted that come under this category. Out of them, below mentioned were considered for this project.

1. DNS Record
2. Website Traffic
3. Age of Domain
4. End Period of Domain

Each of these features are explained and the coded below

In [ ]:
!pip install python-whois

Collecting python-whois
  Downloading python-whois-0.8.0.tar.gz (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.6/109.6 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from python-whois) (0.18.3)
Building wheels for collected packages: python-whois
  Building wheel for python-whois (setup.py) ... done
  Created wheel for python-whois: filename=python_whois-0.8.0-py3-none-any.whl size=103246 sha256=fc9160a781243d207eb27f6a2849be9a266389d722a0859f16caee55180679b9
  Stored in directory: /root/.cache/pip/wheels/10/f1/87/145023b9a206e2e948be6480c61ef3fd3dbb81ef11b6977782
Successfully built python-whois
Installing collected packages: python-whois
Successfully installed python-whois-0.8.0

In [ ]:
# importing required packages for this section
import re
from bs4 import BeautifulSoup
import whois
import urllib
import urllib.request
from datetime import datetime

# 3.2.1. DNS Record
For phishing websites, either the claimed identity is not recognized by the WHOIS database or no records founded for the hostname. If the DNS record is empty or not found then, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 11.DNS Record availability (DNS_Record)
# obtained in the featureExtraction function itself

#3.2.2. Web Traffic
This feature measures the popularity of the website by determining the number of visitors and the number of pages they visit. However, since phishing websites live for a short period of time, they may not be recognized by the Alexa database (Alexa the Web Information Company., 1996). By reviewing our dataset, we find that in worst scenarios, legitimate websites ranked among the top 100,000. Furthermore, if the domain has no traffic or is not recognized by the Alexa database, it is classified as “Phishing”.

If the rank of the domain < 100000, the vlaue of this feature is 1 (phishing) else 0 (legitimate).

In [ ]:
# 12.Weeb traffic
def web_traffic(url):
  try:
    #Filling the whitespaces in the URL if any
    url=urllib.parse.quote(url)
    rank=BeautifulSoup(urllib.request.urlopen("http://data.alexa.com/data?cli=10&dat=s&url=" + url).read(), "xml").find(
        "REACH")['RANK']
    rank=int(rank)
  except TypeError:
    return 1
  if rank < 100000:
    return 1
  return 0

#3.2.3. Age of Domain
This feature can be extracted from WHOIS database. Most phishing websites live for a short period of time. The minimum age of the legitimate domain is considered to be 12 months for this project. Age here is nothing but different between creation and expiration time.

If age of domain > 12 months, the vlaue of this feature is 1 (phishing) else 0 (legitimate).

In [ ]:
# 13.Survival time of domain: The difference between termination time and creation time (Domain_Age)
def domainAge(domain_name):
  creation_date=domain_name.creation_date
  expiration_date=domain_name.expiration_date
  if(isinstance(creation_date,str) or isinstance(expiration_date,str)):
    try:
      creation_date=datetime.striptime(creation_date,'%Y-%m-%d')
      expiration_date=datetime.striptime(expiration_date,'%Y-%m-%d')
    except:
      return 1
  if ((expiration_date is None) or (creation_date is None)):
    return 1
  elif ((type(expiration_date) is list) or (type(creation_date)is list)):
    return 1
  else:
    ageofdomain = abs((expiration_date-creation_date).days)
    if ((ageofdomain/30)<6):
      age=1
    else:
      age=0
  return age

# 3.2.4. End Period of Domain
This feature can be extracted from WHOIS database. For this feature, the remaining domain time is calculated by finding the different between expiration time & current time. The end period considered for the legitimate domain is 6 months or less for this project.

If end period of domain > 6 months, the vlaue of this feature is 1 (phishing) else 0 (legitimate).

In [ ]:
# 14.End time of domain: The difference between termination time and current time (Domain_End)
def domainEnd(domain_name):
  expiration_date = domain_name.expiration_date
  if isinstance(expiration_date,str):
    try:
      expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
    except:
      return 1
  if (expiration_date is None):
      return 1
  elif (type(expiration_date) is list):
      return 1
  else:
    today = datetime.now()
    end = abs((expiration_date - today).days)
    if ((end/30) < 6):
      end = 0
    else:
      end = 1
  return end

# 3.3. HTML and JavaScript based Features
Many features can be extracted that come under this category. Out of them, below mentioned were considered for this project.

1. IFrame Redirection
2. Status Bar Customization
3. Disabling Right Click
4. Website Forwarding

Each of these features are explained and the coded below:

In [ ]:
import requests

# 3.3.1. IFrame Redirection
IFrame is an HTML tag used to display an additional webpage into one that is currently shown. Phishers can make use of the “iframe” tag and make it invisible i.e. without frame borders. In this regard, phishers make use of the “frameBorder” attribute which causes the browser to render a visual delineation.

If the iframe is empty or repsonse is not found then, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 15. IFrame Redirection
def iframe(response):
  if response=="":
    return 1
  else:
    if re.findall(r"[|]", response.text):
      return 0
    else:
      return 1

# 3.3.2. Status Bar Customization
Phishers may use JavaScript to show a fake URL in the status bar to users. To extract this feature, we must dig-out the webpage source code, particularly the “onMouseOver” event, and check if it makes any changes on the status bar

If the response is empty or onmouseover is found then, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 16.Checks the effect of mouse over on status bar (Mouse_Over)
def mouseOver(response):
  if response == "" :
    return 1
  else:
    if re.findall("", response.text):
      return 1
    else:
      return 0

# 3.3.3. Disabling Right Click
Phishers use JavaScript to disable the right-click function, so that users cannot view and save the webpage source code. This feature is treated exactly as “Using onMouseOver to hide the Link”. Nonetheless, for this feature, we will search for event “event.button==2” in the webpage source code and check if the right click is disabled.

If the response is empty or onmouseover is not found then, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 17. checks the status of the right click attribute
def rightClick(response):
  if response=="":
    return 1
  else:
    if re.findall(r"event.button ?=== ?2",response.text):
      return 0
    else:
      return 1

# 3.3.4. Website Forwarding
The fine line that distinguishes phishing websites from legitimate ones is how many times a website has been redirected. In our dataset, we find that legitimate websites have been redirected one time max. On the other hand, phishing websites containing this feature have been redirected at least 4 times.

In [ ]:
# 18.Checks the number of forwardings
def forwarding(response):
  if response=="":
    return 1
  else:
    if len(response.history)<=2:
      return 0
    else:
      return 1

# 4. Computing URL Features
Create a list and a function that calls the other functions and stores all the features of the URL in the list. We will extract the features of each URL and append to this list.

In [ ]:
def featureExtraction(url,label):
  features=[]
  features.append(getDomain(url))
  features.append(havingIP(url))
  features.append(haveAtSign(url))
  features.append(getLength(url))
  features.append(getDepth(url))
  features.append(redirection(url))
  features.append(httpDomain(url))
  features.append(tinyURL(url))
  features.append(prefixSuffix(url))

  #Domain based features (4)
  dns = 0
  try:
    domain_name = whois.whois(urlparse(url).netloc)
  except:
    dns = 1

  features.append(dns)
  features.append(web_traffic(url))
  features.append(1 if dns == 1 else domainAge(domain_name))
  features.append(1 if dns == 1 else domainEnd(domain_name))

  # HTML & Javascript based features (4)
  try:
    response = requests.get(url)
  except:
    response = ""
  features.append(iframe(response))
  features.append(mouseOver(response))
  features.append(rightClick(response))
  features.append(forwarding(response))
  features.append(label)

  return features

# 4.1. Legitimate URLs:

Now, feature extraction is done on legitimate URLs.

In [ ]:
legiurl.shape

(15000, 1)

In [1]:
legi_features=[]
print(legiurl['URLs'])
label=0
for i in range(0,15000):
  url=legiurl['URLs'][1]
  legi_features.append(featureExtraction(url,label))

NameError: name 'legiurl' is not defined

In [ ]:
2